<div class="modal fade" id="term_condition_modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle"
     aria-hidden="true">
    <div style="max-width: 600px !important;" class="modal-dialog" role="document">
        <div class="modal-content">
            <div id="term_form_modal" class="auth-form">
                <div class="modal-header position-relative" style="border-bottom: none !important;">
                    <i style="position: absolute;top:0;right: 0" data-dismiss="modal" aria-label="Close"
                       class="fa fa-times-circle fa-2x"></i>
                </div>
                <div class="modal-body">
                    Customer’s Registration Terms
                    The registration is a vital identification process as it ensures that the sellers and the buyers are creditable and reliable for making transaction.
                     1. Armaiti Mex is responsible for customers authentication based on the registration process as follows:
                    1.1. KYC submitting: A potential customer must fill out the online KYC form accurately and upload the relevant documents as evidence for proving the validation of the information.
                    1.2. Document compliance: Armaiti Mex shall check potential Customers’ Due Diligence (CDD) at the KYC step and based on the data and documents provided by the customer for accuracy and legitimacy. This includes protecting the information against any anticipated threats or hazards to the security or integrity of customer records and information and against unauthorized access to or use of customer information.
                    1.3. Verification:  Armaiti Mex verifies the accepted customers to have a unique User ID (a user name and password) to access to the trading system, registration is free of charge.
                    2. If in any time or any stage of assessment, Armaiti Mex finds out Fake Documents which is the use of counterfeit or altered documents or Outdated Information, cooperation is no longer legally bound.
                    3. In no event sellers and buyers can share their personal account with anyone.
                    4. Customer that receives access privilege shall be subject to all of the laws and instructions of Armaiti Mex and Confidentiality of customers’ information is a key responsibility and obligation of Armaiti Mex.
                    5. The rejected customers by Armaiti Mex, may appeal the decision. Armaiti Mex shall decide, if new or additional information is subsequently brought to the attention, whether the applicant is qualified for having access.
                    6. The customers’ behavior evaluation continues till the activities going on. If they act against Armaiti Mex regulations and instructions or remain inactive for a long time they will receive a warning through the Trading System. If the warning is ignored, Armaiti Mex has the right to ban them from continuing business.
                    7. If the buyer and the seller refuse to provide the related information and documents, Armaiti Mex has the right not to register parties.

                    These Terms and Conditions (the "Terms") govern the services provided to customers by Armaiti Mercantile Exchange (Armaiti Mex), including access to and use of Direct Armaiti Mex' website (WWW.Armaitimex.com).
                    These Terms are applicable from 20 October 2024. The Terms may be updated from time to time without notice to customers. The prevailing version of the Terms is always available at the Website.
                    Questions about these Terms should be directed to: Support@Armaitimex.com
                    Intention
                    This Website is intended for distribution to, or use by any person in any country where such distribution or use would be under the UK law or regulation. All of the commodities referred to in this Website are available to persons resident in any country. Armaiti Mex' services are only available to individuals and companies who are confirmed after registration process. Neither bidders nor suppliers may manipulate the price of any commodity nor may you, or anyone who may gain access, in any way, through you to other pages on this Website, interfere with other user's bids or offers. If any of your transactions cannot be settled in a timely fashion, you hereby acknowledge and agree that Armaiti Mex is authorized to take any reasonable actions to minimize its risks and possible losses.
                    Registration and User ID
                    You must register with Armaiti Mex in order to be eligible to participate in any transaction on this Website. Upon registering, you will receive a User ID and password, which is your identity on the Website and is personal to you. You are responsible for remembering, and safeguarding, your User ID. If you share your User ID with someone else, or you allow a third party to discover your User ID, possible consequences include losing control of your personally- identifiable information and your being legally responsible for any actions taken on the Website by someone else using your User ID. If you have reason to believe that your User ID has been discovered by a third party, you should immediately change your password (please refer to our Privacy Policy to learn how).
                    You should also notify Armaiti Mex immediately by e-mail, at which time you may request the cancellation of one or all orders from you and/or your company. You acknowledge and agree that the cancellation of such order(s) is not guaranteed. Your order(s) will only be cancelled if your request received in Armaiti Mex and matched up with your order(s) before the execution of your order. Please note, however, that market orders are subject to immediate execution upon their receipt by Armaiti Mex, which seriously limits our ability to cancel any such order(s); you may send your cancellation request for minimum 24 hours before the execution and recieve the cancellation confirmation from Armaiti Mex, otherwise it will not be liable for any loss or damage arising from your failure to comply with the requirements of this paragraph.
                    It is your sole and exclusive responsibility to ensure that the information you provide us in the registration process is kept up to date, especially regarding changes to authorized trading personnel, postal and e-mail addresses, and contact telephone numbers. If there are any changes to this information, please contact Armaiti Mex via e-mail at Support@Armaitimex.com. Note that you shall remain responsible and liable for any transactions entered into by unauthorized trading personnel prior to your having informed Armaiti Mex that they are no longer authorized.
                    Links
                    Armaiti Mex has no control over links similiar to or have taken advantage of us, you acknowledge and agree that Armaiti Mex is not responsible for, and has no liability with respect to, the availability (or unavailability) of such sites, for the treatment of your personally identifiable information by such sites, or for the information, products, content or other materials on or available from such sites or resources. If you would like information on any other site's privacy policy, you should contact that party directly, and we encourage you to do so.
                    Usage Limitation 
                    You may not reproduce, duplicate, copy, sell, or otherwise transfer or commercially exploit the Website (or any portion of it), unless you have Armaiti Mex written permission to do so. You may only use the Website in accordance with the terms of this User Agreement, any other terms applicable to the various features of our site and all applicable laws, rules, and regulations. In the event Armaiti Mex (a) believes that you have failed to comply with all terms applicable to your use of the Website or any documents it incorporates by reference; (b) is unable to verify or authenticate any information you provide to it; or (c) believes, in its sole discretion, that your actions may cause legal liability for you, other Website users, or Armaiti Mex, you agree that Armaiti Mex has the right, in its sole discretion and without notice, to terminate your User ID, deactivate or delete your account and all information and files in your account, and prohibit you from accessing your account. Armaiti Mex may also, in its sole discretion and at any time, discontinue the Website, or any part thereof, with or without notice. You agree that you do not have any rights in the Website and that Armaiti Mex will have no liability to you if the Website is discontinued or your ability to access the Website is terminated.
                    Acknowledgement and Agreement
                    a) Your use of Armaiti Mex services and the website is at your own risk. The Features available through the Website are provided to you on an "AS IS" and "AS AVAILABLE" basis. Armaiti Mex expressly disclaims all warranties of any kind, whether express or implied, including but not limited to, the implied warranties of merchantability, fitness for a particular purpose, title, and non-infringement. Because the Website is provided to you "AS IS," you agree that ArmaitiMEX shall not be liable to you or to any third party for any delay in delivery of, or failure to deliver, any of your communications or other information you submit using the Website. Because the Website is provided to you "AS AVAILABLE," you agree that Armaiti Mex shall not be liable to you or to any third party for any modification, suspension, or discontinuance of the Website or of your ability to access it.
                    b) Armaiti Mex also disclaims any warranty that (i) the Website will meet your requirements, (ii) the Website's operation will be uninterrupted, timely, secure, or error-free, (iii) any information or communication that may be obtained from the use of the Website will be accurate or reliable (and Armaiti Mex disclaims any liability for damages that may arise from your reliance on any such information or communication), and (iv) the quality of any products, services, information, or other materials purchased or otherwise obtained by you through the Website will meet your expectations.
                    c) You assume the full responsibility and risk for any damage to your electronic device or other consequences that result from your downloading any information, software, or other materials through the Website. Armaiti Mex shall have no liability for any damage to your electronic device, including loss of data, that results from your downloading any such materials.
                    Liability Limitation
                    You agree that Armaiti Mex shall not be liable for any direct, indirect, incidental, special, consequential, exemplary, or punitive damage, including but not limited to damages for lost profits (even if Armaiti Mex has been advised of the possibility of such damages), that result from (a) your use of or inability of the website; (b) access to or alteration of your personally-identifiable information or other information in an unauthorized manner; (d) representation or conduct of any third party related to the website, including our advertisers and business partners; or (e) any other website matter relating to the website.
                    General
                    You agree that this User Agreement describes the entire agreement between us with respect to its subject matter. The Website is operated under the laws of UK and it will control the terms and conditions provided in this User Agreement, without giving effect to any principles of conflict of laws. Any dispute arising out of or in connection with the Terms, including any disputes regarding the existence, validity or termination thereof, shall be settled by arbitration arranged by The UK law.

                </div>

                <div class="modal-footer">
                    <button data-dismiss="modal" aria-label="Close" style="background: white;color: black" type="button" class="btn btn-block">
                        Ok
                    </button>
                </div>

            </div>
        </div>
    </div>
</div>
